# Generated by Django 3.2.7 on 2021-12-02 22:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='NULL', max_length=100, verbose_name='Ф.И.О.')),
                ('phone_num', models.CharField(default='+11111111111', max_length=12, unique=True, verbose_name='Номер телефона')),
                ('mail', models.CharField(default='NULL', max_length=100, verbose_name='@mail')),
                ('id_tele', models.IntegerField(blank=True, default=None, null=True, verbose_name='Телеграм id')),
                ('name_tele', models.CharField(default='NULL', max_length=50, verbose_name='телеграм имя')),
            ],
            options={
                'verbose_name': 'Все Сотрудники',
                'verbose_name_plural': 'Все Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(max_length=1024)),
                ('msg_id', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Редактирование сообщений бота',
                'verbose_name_plural': 'Редактирование сообщений бота',
            },
        ),
        migrations.CreateModel(
            name='MY_CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
            options={
                'verbose_name': 'Существующие роли',
                'verbose_name_plural': 'Существующие роли',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('allemployment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BotShell.allemployment')),
            ],
            options={
                'verbose_name': 'Подчинённый',
                'verbose_name_plural': 'Подчинённые',
            },
            bases=('BotShell.allemployment',),
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('allemployment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BotShell.allemployment')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
            bases=('BotShell.allemployment',),
        ),
        migrations.CreateModel(
            name='Сolleague',
            fields=[
                ('allemployment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BotShell.allemployment')),
            ],
            options={
                'verbose_name': 'Коллега',
                'verbose_name_plural': 'Коллеги',
            },
            bases=('BotShell.allemployment',),
        ),
        migrations.CreateModel(
            name='TopManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleagues', models.ManyToManyField(blank=True, related_name='coll_topm', to='BotShell.AllEmployment', verbose_name='Коллеги, которых осталось оценить')),
                ('employers', models.ManyToManyField(blank=True, related_name='employee_topm', to='BotShell.AllEmployment', verbose_name='Подчинённые, которых осталось оценить')),
                ('fio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BotShell.allemployment')),
                ('teamLeader', models.ManyToManyField(blank=True, related_name='lead_topm', to='BotShell.AllEmployment', verbose_name='Руководители, которых осталось оценить')),
            ],
            options={
                'verbose_name': 'Топ менеджер',
                'verbose_name_plural': 'Топ менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleagues', models.ManyToManyField(blank=True, related_name='colleg_spec', to='BotShell.AllEmployment', verbose_name='Коллеги, которых осталось оценить')),
                ('employment', models.ManyToManyField(blank=True, related_name='employee_spec', to='BotShell.AllEmployment', verbose_name='Подчинённые, которых осталось оценить')),
                ('fio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BotShell.allemployment')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleagues', models.ManyToManyField(blank=True, related_name='colleg', to='BotShell.AllEmployment', verbose_name='Коллеги, которых осталось оценить')),
                ('employers', models.ManyToManyField(blank=True, related_name='employee', to='BotShell.AllEmployment', verbose_name='Подчинённые, которых осталось оценить')),
                ('fio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BotShell.allemployment')),
                ('teamLeader', models.ManyToManyField(blank=True, related_name='lead', to='BotShell.AllEmployment', verbose_name='Руководители, которых осталось оценить')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.AddField(
            model_name='allemployment',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='BotShell.MY_CHOICES', verbose_name='Роль сотрудника'),
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='NULL', max_length=100, verbose_name='Ф.И.О.')),
                ('phone_num', models.CharField(default='+398989889', max_length=100, unique=True, verbose_name='Номер телефона')),
                ('mail', models.CharField(default='NULL', max_length=100, verbose_name='@mail')),
                ('id_tele', models.IntegerField(blank=True, default=None, null=True, verbose_name='Телеграм id')),
                ('name_tele', models.CharField(default='NULL', max_length=50, verbose_name='телеграм имя')),
                ('colleagues', models.ManyToManyField(blank=True, related_name='_BotShell_hr_colleagues_+', to='BotShell.Hr', verbose_name='Сотрудники для оценивания из HR')),
                ('employments', models.ManyToManyField(blank=True, to='BotShell.Employment', verbose_name='Сотрудники для оценивания из списка подчинённых')),
                ('team_leaders', models.ManyToManyField(blank=True, to='BotShell.TeamLeader', verbose_name='Сотрудники для оценивания из списка руководителей')),
            ],
            options={
                'verbose_name': 'HR1',
                'verbose_name_plural': 'HR1',
            },
        ),
    ]
