# Generated by Django 3.2.7 on 2021-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allemployment',
            name='job_type',
            field=models.CharField(choices=[('specialist', 'Специалист'), ('manager', 'Менеджер'), ('TopManager', 'Топ-Менеджер')], default=1, max_length=25, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='markBySomeone',
            field=models.BooleanField(default=False, verbose_name='Был ли уже оценен кем-либо'),
        ),
        migrations.AddField(
            model_name='manager',
            name='markEnd',
            field=models.BooleanField(default=False, verbose_name='Закончил оченку'),
        ),
        migrations.AddField(
            model_name='manager',
            name='markStart',
            field=models.BooleanField(default=False, verbose_name='Начал оченку'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='markBySomeone',
            field=models.BooleanField(default=False, verbose_name='Был ли уже оценен кем-либо'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='markEnd',
            field=models.BooleanField(default=False, verbose_name='Закончил оченку'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='markStart',
            field=models.BooleanField(default=False, verbose_name='Начал оченку'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='manyToMark',
            field=models.IntegerField(default=0, verbose_name='осталось оценить'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='markBySomeone',
            field=models.BooleanField(default=False, verbose_name='Был ли уже оценен кем-либо'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='markCounter',
            field=models.IntegerField(default=0, verbose_name='сколько оценено'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='markEnd',
            field=models.BooleanField(default=False, verbose_name='Закончил оченку'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='markStart',
            field=models.BooleanField(default=False, verbose_name='Начал оченку'),
        ),
    ]
