# Generated by Django 3.2.7 on 2021-12-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0002_auto_20211204_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmanager',
            name='fio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obj_from_all_empl', to='BotShell.allemployment'),
        ),
    ]
