# Generated by Django 3.2.7 on 2021-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0003_alter_topmanager_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmanager',
            name='counterMarkedMe',
            field=models.IntegerField(default=0, verbose_name='Сколько меня оценило'),
        ),
    ]
