# Generated by Django 3.2.7 on 2021-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0004_topmanager_countermarkedme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='markBySomeone',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='markBySomeone',
        ),
        migrations.RemoveField(
            model_name='topmanager',
            name='markBySomeone',
        ),
        migrations.AddField(
            model_name='manager',
            name='counterMarkedMe',
            field=models.IntegerField(default=0, verbose_name='Сколько меня оценило'),
        ),
        migrations.AddField(
            model_name='manager',
            name='manyToMark',
            field=models.IntegerField(default=0, verbose_name='осталось оценить'),
        ),
        migrations.AddField(
            model_name='manager',
            name='markCounter',
            field=models.IntegerField(default=0, verbose_name='сколько оценено'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='counterMarkedMe',
            field=models.IntegerField(default=0, verbose_name='Сколько меня оценило'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='manyToMark',
            field=models.IntegerField(default=0, verbose_name='осталось оценить'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='markCounter',
            field=models.IntegerField(default=0, verbose_name='сколько оценено'),
        ),
    ]
