# Generated by Django 3.2.7 on 2021-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0005_auto_20211204_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='employment',
        ),
        migrations.AddField(
            model_name='specialist',
            name='teamLeader',
            field=models.ManyToManyField(blank=True, related_name='lead_topm', to='BotShell.AllEmployment', verbose_name='Руководители, которых осталось оценить'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='teamLeader',
            field=models.ManyToManyField(blank=True, related_name='lead_m', to='BotShell.AllEmployment', verbose_name='Руководители, которых осталось оценить'),
        ),
        migrations.AlterField(
            model_name='topmanager',
            name='teamLeader',
            field=models.ManyToManyField(blank=True, related_name='lead_spec', to='BotShell.AllEmployment', verbose_name='Руководители, которых осталось оценить'),
        ),
    ]
