# Generated by Django 3.2.7 on 2021-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0006_auto_20211204_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='markByHimSelf',
            field=models.BooleanField(default=False, verbose_name='Оценил сам себя'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='markByHimSelf',
            field=models.BooleanField(default=False, verbose_name='Оценил сам себя'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='markByHimSelf',
            field=models.BooleanField(default=False, verbose_name='Оценил сам себя'),
        ),
    ]
