# Generated by Django 3.2.7 on 2021-12-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0007_auto_20211204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployment',
            name='job_type',
            field=models.CharField(choices=[('specialist', 'Специалист'), ('manager', 'Менеджер'), ('TopManager', 'Топ-Менеджер'), ('HR', 'HR')], max_length=25, verbose_name='Должность'),
        ),
    ]
