# Generated by Django 3.2.7 on 2021-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0009_auto_20211204_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlines',
            options={'verbose_name': 'Дедлайн', 'verbose_name_plural': 'Дедлайны'},
        ),
        migrations.AddField(
            model_name='manager',
            name='reportIsReady',
            field=models.BooleanField(default=False, verbose_name='Готов ли отчёт по этому человеку'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='reportIsReady',
            field=models.BooleanField(default=False, verbose_name='Готов ли отчёт по этому человеку'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='reportIsReady',
            field=models.BooleanField(default=False, verbose_name='Готов ли отчёт'),
        ),
    ]
