# Generated by Django 3.2.7 on 2021-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0010_auto_20211204_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployment',
            name='fio',
            field=models.CharField(default='NULL', max_length=100, unique=True, verbose_name='Ф.И.О.'),
        ),
    ]
