# Generated by Django 3.2.7 on 2021-12-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0011_alter_allemployment_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_rate', models.IntegerField(default=120, verbose_name='Напоминание сотрудником, не закончившим оценку, поисходит раз в часов: ')),
                ('time_from_last_mail', models.IntegerField(default=0, verbose_name='Прошло часов с педыдущего уведомления: ')),
            ],
        ),
        migrations.AlterField(
            model_name='specialist',
            name='reportIsReady',
            field=models.BooleanField(default=False, verbose_name='Готов ли отчёт'),
        ),
    ]
