# Generated by Django 3.2.7 on 2021-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0014_auto_20211205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн для сотрудника'),
        ),
    ]
