# Generated by Django 3.2.7 on 2021-12-05 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0016_auto_20211205_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(max_length=1024, verbose_name='Текст для рассылки')),
                ('send_or_not', models.BooleanField(default=False, verbose_name='Произвести рассылку этого сообщения прямо сейчас')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылка',
            },
        ),
    ]
