# Generated by Django 3.2.7 on 2021-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0018_remove_allemployment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployment',
            name='phone_num',
            field=models.CharField(default='+11111111111', max_length=25, unique=True, verbose_name='Номер телефона'),
        ),
    ]
