# Generated by Django 3.2.7 on 2021-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0020_auto_20211216_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='all_employers',
        ),
        migrations.AddField(
            model_name='manager',
            name='all_employers',
            field=models.CharField(default='NULL', max_length=10000, verbose_name='Все подчиненные'),
        ),
        migrations.RemoveField(
            model_name='topmanager',
            name='all_employers',
        ),
        migrations.AddField(
            model_name='topmanager',
            name='all_employers',
            field=models.CharField(default='NULL', max_length=10000, verbose_name='Все подчиненные'),
        ),
    ]
