# Generated by Django 3.2.7 on 2021-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0021_auto_20211216_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmanager',
            name='all_employers',
            field=models.CharField(default='', max_length=10000, verbose_name='Все подчиненные'),
        ),
    ]
