# Generated by Django 3.2.7 on 2021-12-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0027_alter_manager_all_employers'),
    ]

    operations = [
        migrations.AddField(
            model_name='allemployment',
            name='HR',
            field=models.BooleanField(default=False, verbose_name='Является ли эшаром'),
        ),
        migrations.AlterField(
            model_name='allemployment',
            name='job_type',
            field=models.CharField(choices=[('specialist', 'Специалист'), ('manager', 'Менеджер'), ('TopManager', 'Топ-Менеджер')], max_length=25, verbose_name='Должность'),
        ),
    ]
